# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ui\delete_confirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(562, 245)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(24, 24, 24, 24)
        self.verticalLayout_2.setSpacing(16)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.info_frame = QtWidgets.QFrame(Dialog)
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.info_frame)
        self.horizontalLayout_2.setContentsMargins(16, 16, 16, 16)
        self.horizontalLayout_2.setSpacing(16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.icon_label = QtWidgets.QLabel(self.info_frame)
        self.icon_label.setMinimumSize(QtCore.QSize(24, 0))
        self.icon_label.setMaximumSize(QtCore.QSize(24, 16777215))
        self.icon_label.setText("")
        self.icon_label.setObjectName("icon_label")
        self.horizontalLayout_2.addWidget(self.icon_label)
        self.text_frame = QtWidgets.QFrame(self.info_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text_frame.setFont(font)
        self.text_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.text_frame.setObjectName("text_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.text_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(self.text_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.info_label = QtWidgets.QLabel(self.text_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_label.setFont(font)
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.text_frame)
        self.verticalLayout_2.addWidget(self.info_frame)
        self.buttons_frame = QtWidgets.QFrame(Dialog)
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_frame.setObjectName("buttons_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttons_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(16)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel_document_pushButton = TertiaryButton(self.buttons_frame)
        self.cancel_document_pushButton.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancel_document_pushButton.setFont(font)
        self.cancel_document_pushButton.setObjectName("cancel_document_pushButton")
        self.horizontalLayout.addWidget(self.cancel_document_pushButton)
        self.delete_document_pushButton = PrimaryButton(self.buttons_frame)
        self.delete_document_pushButton.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delete_document_pushButton.setFont(font)
        self.delete_document_pushButton.setObjectName("delete_document_pushButton")
        self.horizontalLayout.addWidget(self.delete_document_pushButton)
        self.verticalLayout_2.addWidget(self.buttons_frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_label.setText(_translate("Dialog", "Подтверждение удаления"))
        self.info_label.setText(_translate("Dialog", "Введите “Подтвердить” для удаления документа "))
        self.cancel_document_pushButton.setText(_translate("Dialog", "Отменить"))
        self.delete_document_pushButton.setText(_translate("Dialog", "Удалить документ"))
from ..custom_widgets import PrimaryButton, TertiaryButton
