# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/notification.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Notification(object):
    def setupUi(self, Notification):
        Notification.setObjectName("Notification")
        Notification.resize(398, 64)
        Notification.setMinimumSize(QtCore.QSize(0, 64))
        Notification.setStyleSheet("border-radius: 0px;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Notification)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.notify_type_line_frame = QtWidgets.QFrame(Notification)
        self.notify_type_line_frame.setMaximumSize(QtCore.QSize(16, 16777215))
        self.notify_type_line_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.notify_type_line_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.notify_type_line_frame.setObjectName("notify_type_line_frame")
        self.horizontalLayout.addWidget(self.notify_type_line_frame)
        self.Icon_label = QtWidgets.QLabel(Notification)
        self.Icon_label.setMinimumSize(QtCore.QSize(56, 0))
        self.Icon_label.setMaximumSize(QtCore.QSize(56, 16777215))
        self.Icon_label.setText("")
        self.Icon_label.setObjectName("Icon_label")
        self.horizontalLayout.addWidget(self.Icon_label)
        self.texts_frame = QtWidgets.QFrame(Notification)
        self.texts_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.texts_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.texts_frame.setObjectName("texts_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.texts_frame)
        self.verticalLayout.setContentsMargins(0, 16, 0, 16)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.texts_frame)
        self.label.setMinimumSize(QtCore.QSize(280, 0))
        self.label.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Description = QtWidgets.QLabel(self.texts_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Description.setFont(font)
        self.Description.setObjectName("Description")
        self.verticalLayout.addWidget(self.Description)
        self.horizontalLayout.addWidget(self.texts_frame)
        self.close_pushButton = QtWidgets.QPushButton(Notification)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_pushButton.sizePolicy().hasHeightForWidth())
        self.close_pushButton.setSizePolicy(sizePolicy)
        self.close_pushButton.setMinimumSize(QtCore.QSize(52, 0))
        self.close_pushButton.setMaximumSize(QtCore.QSize(52, 16777215))
        self.close_pushButton.setText("")
        self.close_pushButton.setObjectName("close_pushButton")
        self.horizontalLayout.addWidget(self.close_pushButton)

        self.retranslateUi(Notification)
        QtCore.QMetaObject.connectSlotsByName(Notification)

    def retranslateUi(self, Notification):
        _translate = QtCore.QCoreApplication.translate
        Notification.setWindowTitle(_translate("Notification", "Form"))
        self.label.setText(_translate("Notification", "Label"))
        self.Description.setText(_translate("Notification", "Description"))
